### ISSUE TITLE
value partially assigned here after move

### ISSUE THREAD

**Issue by AlexSpain** [origolab/origo#1]
ethcore/src/engines/clique/mod.rs:204:4
    |
190 |         let mut engine = Clique {
    |             ---------- move occurs because `engine` has type `engines::clique::Clique`, which does not implement the `Copy` trait
...
201 |         let res = Arc::new(engine);
    |                            ------ value moved here
...
204 |             engine.step_service = Some(StepService::start(Arc::downgrade(&res) as Weak<Engine<_>>));
    |             ^^^^^^^^^^^^^^^^^^^ value partially assigned here after move

rustc 1.42.0 (b8cedc004 2020-03-09)

**Comment by AlexSpain** [comment]
fixed

**Comment by sniper-noob** [comment]
Hi. can you share the fix?
